'use strict';
let data, selected = location.hash.slice(1), lastRender = '';
const $ = id => document.getElementById(id);
const seen = JSON.parse(localStorage.getItem('housing-inbox-seen') || '{}');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl = value => { try { const u = new URL(value, location.origin); return ['http:','https:'].includes(u.protocol) ? esc(u.href) : ''; } catch { return ''; } };
const fmt = value => value ? new Date(value).toLocaleString('en-US', {timeZone:'America/Los_Angeles',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}) : 'Not checked';
const shortDate = value => value ? new Date(value).toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric'}) : '';
const sourceNames = {furnishedfinder:'Furnished Finder',spareroom:'SpareRoom',zillow:'Zillow',gmail:'Gmail · tianjiahe11',craigslist:'Craigslist',supost:'SUpost',apartments:'Apartments.com',sms:'Text messages',rednote:'Rednote'};
const sourceTitle = key => sourceNames[key] || key;
const tourLabels = {confirmed:'Confirmed viewing',awaiting_confirmation:'Proposed · awaiting confirmation',postponed_by_host:'Postponed by host',canceled_unavailable:'Canceled · room taken',past_outcome_unknown:'Past viewing · outcome unknown'};
function unread(t){return t.messages.some(m=>m.direction==='incoming' && !m.automated && new Date(m.at || 0).getTime() > (seen[t.id] || 0));}
function filtered(){const q=$('search').value.toLowerCase(), f=$('filter').value, c=$('channel').value;return data.threads.filter(t=>(c==='all'||t.source===c)&&(!q||JSON.stringify(t).toLowerCase().includes(q))&&(f==='all'||f==='reply'&&t.needs_reply||f==='unread'&&unread(t)||f==='tours'&&t.tour||f==='unsent'&&!t.contacted));}
function renderList(){const threads=filtered();$('count').textContent=`${threads.length} conversations · ${data.verified_outgoing} outgoing messages verified in the outreach log`;
 $('thread-list').innerHTML=threads.map(t=>{const m=t.messages[t.messages.length-1];return `<button class="thread ${t.id===selected?'active':''}" data-thread="${esc(t.id)}"><div class="row"><span class="name">${unread(t)?'<span class="unread"></span>':''}${esc(t.contact?.host||t.host||t.title.split(' · ')[0])}</span><span class="date">${shortDate(t.latest_at)}</span></div><p class="property">${esc(t.title)}</p><p class="snippet">${esc(m?(m.direction==='outgoing'?'You: ':'')+m.body:t.note||'No message has been sent.')}</p>${t.needs_reply?'<span class="label">Latest message from host</span>':t.tour?`<span class="label">${esc(tourLabels[t.tour.status]||t.tour.status)}</span>`:''}</button>`;}).join('')||'<p class="empty">No matching conversations.</p>';
 document.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>choose(b.dataset.thread));}
function choose(id){selected=id;location.hash=id;seen[id]=Date.now();localStorage.setItem('housing-inbox-seen',JSON.stringify(seen));$('work').classList.add('show-detail');lastRender='';renderList();renderDetail();}
function renderDetail(){const t=data.threads.find(t=>t.id===selected);if(!t)return;const signature=JSON.stringify(t);if(lastRender===signature)return;lastRender=signature;
 const links=[...new Set(t.messages.map(m=>m.thread_url).filter(Boolean))];const tour=t.tour;const r=t.rating;
 const messages=[...t.messages].reverse().map(m=>`<article class="message ${esc(m.direction)} ${m.kind==='summary'?'summary':''}"><div class="message-meta"><span>${esc(m.direction==='outgoing'?'You':m.sender||'Host')} · ${esc(m.channel)}</span><span>${esc(m.at?fmt(m.at):m.date_label||'Time not recorded')}</span></div><div class="bubble">${esc(m.body.replace(/\n{3,}/g,'\n\n'))}</div><div class="message-foot">${m.kind==='summary'?'Earlier summary · not a verbatim message':m.automated?'Automated platform notice':esc(m.delivery||'')}${m.time_precision==='message group'?' · time shown for this message group':''}${m.thread_url?` · <a href="${safeUrl(m.thread_url)}" target="_blank" rel="noopener noreferrer">Original ↗</a>`:''}${m.also_seen?.some(a=>a.channel.includes('email'))?' · also received by email':''}</div></article>`).join('');
 $('detail').innerHTML=`<div class="detail-head"><button class="btn back" id="back">← Conversations</button><div class="eyebrow">${esc(t.source)}</div><div class="headrow"><h2>${esc(t.title)}</h2>${t.rent?`<div class="rent">$${t.rent.toLocaleString()}<small>/ month advertised</small></div>`:''}</div><p class="property-line">${esc(t.area)}${t.contact?.phone?' · '+esc(t.contact.phone):''}</p><div class="tags">${t.channels.map(c=>`<span class="tag">${esc(c)}</span>`).join('')}</div><div class="links">${links.slice(0,4).map((u,i)=>`<a href="${safeUrl(u)}" target="_blank" rel="noopener noreferrer">${u.includes('mail.google')?'Open email':u.includes('furnishedfinder')?'Reply on Furnished Finder':u.includes('spareroom')?'Reply on SpareRoom':u.includes('zillow')?'Reply on Zillow':'Open conversation'} ↗</a>`).join('')}${t.url?`<a href="${safeUrl(t.url)}" target="_blank" rel="noopener noreferrer">Listing ↗</a><a href="/#${esc(t.id)}">Property details</a>`:''}</div>${tour?`<div class="tour ${tour.status!=='confirmed'?'warning':''}"><strong>${esc(tourLabels[tour.status]||tour.status)}${tour.confirmed_start||tour.proposed_start?' · '+fmt(tour.confirmed_start||tour.proposed_start)+' PT':''}</strong>${esc(tour.note)}</div>`:''}${r?`<details class="rating"><summary>Photo review and value</summary><div class="score"><span>Apparent cleanliness <b>${r.cleanliness??'Unrated'}${r.cleanliness?' / 5':''}</b></span><span>Modernity <b>${r.modernity??'Unrated'}${r.modernity?' / 5':''}</b></span><span>Value <b>${r.value??'Unrated'}${r.value?' / 5':''}</b></span></div><p>${esc(r.note)}</p><div class="photos">${(t.photos||[]).slice(0,10).map(p=>`<a href="/maps/${encodeURIComponent(p.file)}" target="_blank"><img src="/maps/${encodeURIComponent(p.file)}" alt="Advertiser’s property photo" loading="lazy"></a>`).join('')}</div></details>`:''}</div>${t.channels.some(c=>c.includes('SMS'))?'<div class="notice">SMS shown here came from the screenshots you supplied. New texts are not connected to monitoring.</div>':''}<div class="messages">${messages||'<div class="empty">No verified messages yet.<br>'+esc(t.note||'')+'</div>'}</div>`;
 $('back').onclick=()=>$('work').classList.remove('show-detail');}
function renderHealth(){const primary=['furnishedfinder','spareroom','zillow','gmail'];let good=0;const now=Date.now();
 for(const k of primary){const s=data.sources[k];if(s?.status==='ok'&&now-new Date(s.last_success).getTime()<90*60000)good++;}
 const running=data.running&&now-new Date(data.running.started_at).getTime()<20*60000;
 $('check-now').disabled=!!running;$('check-now').textContent=running?'Checking…':'Check now';
 const last=data.scheduler.last_successful_check;
 $('monitor-summary').innerHTML=`<span class="dot ${good<4?'bad':''}"></span><b>${running?'Checking connected channels…':good===4?'Connected channels up to date':good?`${good} of 4 connected inboxes current`:'Monitoring needs attention'}</b> · ${last?'Last full check '+fmt(last)+' PT':'No successful full check yet'}`;
 const gaps=Object.values(data.sources).filter(s=>s.status==='not_connected').length;
 $('coverage-summary').textContent=`${gaps} connection gaps · details`;
 $('health-grid').innerHTML=Object.entries(data.sources).map(([k,s])=>{const stale=s.last_success&&now-new Date(s.last_success).getTime()>90*60000;const label=s.status==='not_connected'?'Not connected':s.status!=='ok'?'Check failed':stale?'Stale':s.via?'Via email':'Checked';const detail=s.status==='error'?'This check could not finish. Previous messages are kept; the next check will retry.':s.detail;return `<div class="health-item"><span class="status ${label==='Checked'||label==='Via email'?'':s.status==='not_connected'?'warn':'bad'}">${esc(label)}</span><strong>${esc(sourceTitle(k))}</strong><p>${esc(detail)}</p>${s.last_success?`<p>Last success: ${fmt(s.last_success)} PT</p>`:''}</div>`;}).join('');
 $('run-history').innerHTML=`<p><b>Schedule:</b> ${esc(data.scheduler.schedule_note||'Not configured')}. ${esc(data.scheduler.requires||'')}</p>${data.scheduler.previous_failure?'<p>The earlier monitor failed to start and has been replaced.</p>':''}`+data.runs.slice(0,8).map(r=>`<p>${fmt(r.started_at)} PT · <b>${esc(r.status.replace(/_/g,' '))}</b>${r.trigger==='launchd'?' · background service':''} · ${r.imported_records} new source records${r.errors.length?' · incomplete check; previous messages kept':''}</p>`).join('');
 $('footer').textContent=`Private messages stay on this computer. View refreshes every 30 seconds; messages sync hourly while this Mac is awake and Chrome is connected. All times Pacific. Last collector update: ${fmt(data.updated_at)}.`;
}
async function refresh(){try{const r=await fetch('/api/inbox',{cache:'no-store'});if(!r.ok)throw Error('Inbox unavailable ('+r.status+')');data=await r.json();$('app-error').textContent='';const c=$('channel').value;const platforms=[...new Set(data.threads.map(t=>t.source))].sort();$('channel').innerHTML='<option value="all">All platforms</option>'+platforms.map(x=>`<option>${esc(x)}</option>`).join('');$('channel').value=c;if(!selected||!data.threads.some(t=>t.id===selected))selected=data.threads[0]?.id;renderList();renderDetail();renderHealth();}catch(e){$('app-error').textContent='Could not refresh the inbox. '+e.message;}}
$('search').oninput=renderList;$('filter').onchange=renderList;$('channel').onchange=renderList;
$('check-now').onclick=async()=>{try{$('check-now').disabled=true;const r=await fetch('/api/inbox/check',{method:'POST',headers:{'X-Housing-Inbox':'1'}});const x=await r.json();if(!r.ok)throw Error(x.error||'Check could not start');$('check-feedback').textContent=x.message;$('health-panel').open=true;setTimeout(refresh,1500);}catch(e){$('app-error').textContent=e.message;$('check-now').disabled=false;}};
$('import-open').onclick=()=>{$('import-property').innerHTML=data.threads.filter(t=>t.url).map(t=>`<option value="${esc(t.id)}">${esc(t.title)}</option>`).join('');$('import-property').value=selected;$('import-dialog').showModal();};
$('import-cancel').onclick=()=>$('import-dialog').close();
$('import-form').onsubmit=async e=>{e.preventDefault();const value={listing_id:$('import-property').value,sender:$('import-sender').value,body:$('import-body').value,at:$('import-date').value?new Date($('import-date').value).toISOString():null};try{const r=await fetch('/api/inbox/import',{method:'POST',headers:{'Content-Type':'application/json','X-Housing-Inbox':'1'},body:JSON.stringify(value)});if(!r.ok)throw Error('Message could not be saved');$('import-dialog').close();$('import-form').reset();await refresh();choose(value.listing_id);}catch(e){$('app-error').textContent=e.message;}};
window.addEventListener('hashchange',()=>{if(location.hash.slice(1)!==selected)choose(location.hash.slice(1));});
refresh();setInterval(refresh,30000);
